version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: chat-application-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realtime-chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/realtime-chat
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma db push &&
             npm start"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
